version: '3.8'

services:
  # mongo:
  #   image: mongo
  #   ports:
  #     - '27018:27017'
  #   volumes:
  #     - data:/data/db
  #   networks:
  #     - my_network
  # backend:
  #   build: ./backend
  #   ports:
  #     - '8000:8000'
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - mongo
  #   networks:
  #     - my_network

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    # depends_on:
    #   - backend
    networks:
      - my_network

volumes:
  data:
networks:
  my_network:
  
